
### 회원가입
POST  http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "test5@test.com",
    "password": "12345678",
    "nickname": "test5"
}

### 로그인
POST  http://localhost:8080/auth/signin
Content-Type: application/json

{
    "email": "test5@test.com",
    "password": "12345678"
}

### test
GET  http://localhost:8080/auth/

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTcwNTQwMDg5M30.2kKYvwilMs5FQQNf_GUMWoeFu5cIbJ-TFp-G3eqYngE